#!/bin/bash
set -e -x

cd $(dirname $0)/..
. scripts/version.sh

TAGS="netcgo osusergo static_build"
LDFLAGS="-w -s -X main.version=$VERSION"
CGO_ENABLED=0 go build -v -tags "$TAGS" -ldflags "$LDFLAGS" -o bin/wharfie ./main.go
