#!/bin/bash
set -e -x

cd $(dirname $0)/..
. scripts/version.sh

TAGS="netcgo osusergo static_build"
LDFLAGS="-w -s -X main.version=$VERSION"
CGO_ENABLED=0 go build -v -tags "$TAGS" -ldflags "$LDFLAGS" -o bin/wharfie-amd64 ./main.go

if [ "$CROSS" = "true" ] && [ "$ARCH" = "amd64" ]; then
    CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -tags "$TAGS" -ldflags "$LDFLAGS" -o bin/wharfie-arm64 
fi