#!/bin/bash
set -e -x

cd $(dirname $0)/..
. scripts/version.sh

./scripts/test
./scripts/build
./scripts/build-plugins

mkdir -p dist/artifacts

for FILE in bin/wharfie* bin/plugins/*; do
  cp ${FILE} dist/artifacts/$(basename $FILE)
done

sed "s/  - name: .*/&-amd64/" package/config.yaml > dist/artifacts/config-amd64.yaml
sed "s/  - name: .*/&-arm64/" package/config.yaml > dist/artifacts/config-arm64.yaml
