#!/bin/bash
set -e -x

cd $(dirname $0)/..
. scripts/version.sh

./scripts/test
./scripts/build
./scripts/build-plugins

mkdir -p dist/artifacts

for FILE in bin/wharfie bin/plugins/*; do
  cp ${FILE} dist/artifacts/$(basename $FILE)-${ARCH}
done

sed "s/  - name: .*/&-${ARCH}/" package/config.yaml > dist/artifacts/config-${ARCH}.yaml
